name: secondjob
on: [push, workflow_dispatch]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: print working directory
        run: |
         node -v
         git --version
         