name: secondjob
on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'

      - name: Print Node.js version
        run: node -v
      - name: install dependices
        run: npm install --frozen-lockfile
      - name: start
        run: npm run start

